# Importar módulos

Los módulos son programas que amplían las funciones y clases de Python para realizar tareas específicas. Los modulos son librerias igual que R. 

Lo habitual cuando se desarrollan aplicaciones es que los programas se vuelvan muy largos. En estos casos conviene organizar el código en distintos archivos dependiendo de su funcionalidad. Con esto conseguimos:

* que el mantenimiento sea más fácil. 
* reutilizar código; usar una función en varias aplicaciones sin necesidad de copiarla varias veces.

Estos archivos se llaman __módulos__ y tienen extensión __`py`__.
* Contienen definición de funciones
* Datos
* Definición de clases, etc.

En https://docs.python.org/3/py-modindex.html se puede encontar el índice de módulos de Python.




## Módulos estándar

Python viene con una biblioteca de módulos estándar. Algunos módulos se integran en el intérprete; estos proveen acceso
a operaciones que no son parte del núcleo del lenguaje pero que sin embargo están integrados, tanto por eficiencia como
para proveer acceso a primitivas del sistema operativo, como llamadas al sistema.

Para listar los módulos que tenemos instalados y que por tanto podemos importar en nuestros programas, basta con ejecutar el siguiente comando:
 

In [ ]:
!conda list

Si queremos usar un módulo que no está en la lista, tendremos que instalarlo primero. Para ello podemos usar el comando `conda install` desde una ventana de comandos. Por ejemplo para instalar el módulo `pymysql` escribiremos:

In [ ]:
conda install pymysql

Los módulos que tenemos disponibles se pueden importar de las siguientes formas:
    * from modulo import * 
    * import modulo 
    * import modulo as alias

Dependiendo de cómo hayamos importado el módulo, así tendremos que utilizarlo.

In [4]:
from numpy import array    # Importamos solo la función array
a = array( [2,3,4] )       
a

array([2, 3, 4])

In [5]:
import numpy                      # Importamos todo el módulo
a = numpy.array( [2,3,4] )       
a

array([2, 3, 4])

In [6]:
import numpy as np
a = np.array( [2,3,4] )       # se accede con el alias a la función array
a

array([2, 3, 4])

## Operaciones disponibles en un módulo

La función integrada `dir()` se usa para encontrar qué nombres define un módulo. Devuelve una lista ordenada de cadenas:

In [7]:
import math
dir(math)    # math es un módulo#dir te ofrece todas als operaciones que puedes hacer
#nombre de la liberria.tabulador y te ofrece todas las opciones

['__doc__',
 '__loader__',
 '__name__',
 '__package__',
 '__spec__',
 'acos',
 'acosh',
 'asin',
 'asinh',
 'atan',
 'atan2',
 'atanh',
 'ceil',
 'copysign',
 'cos',
 'cosh',
 'degrees',
 'e',
 'erf',
 'erfc',
 'exp',
 'expm1',
 'fabs',
 'factorial',
 'floor',
 'fmod',
 'frexp',
 'fsum',
 'gamma',
 'gcd',
 'hypot',
 'inf',
 'isclose',
 'isfinite',
 'isinf',
 'isnan',
 'ldexp',
 'lgamma',
 'log',
 'log10',
 'log1p',
 'log2',
 'modf',
 'nan',
 'pi',
 'pow',
 'radians',
 'sin',
 'sinh',
 'sqrt',
 'tan',
 'tanh',
 'tau',
 'trunc']

In [8]:
import math as mt
mt.sin(34)

0.5290826861200238

In [9]:
mt.pi

3.141592653589793

In [10]:
mt.sqrt(24)

4.898979485566356

In [11]:
help(mt.pow)    # accede a la documentación de la función pow

Help on built-in function pow in module math:

pow(...)
    pow(x, y)
    
    Return x**y (x to the power of y).



-------------