# Acceso y recorrido de arrays

In [9]:
import numpy as np

a = np.arange(15) ** 3
a

array([   0,    1,    8,   27,   64,  125,  216,  343,  512,  729, 1000,
       1331, 1728, 2197, 2744])

In [10]:
b = a.reshape(5, 3)
b

array([[   0,    1,    8],
       [  27,   64,  125],
       [ 216,  343,  512],
       [ 729, 1000, 1331],
       [1728, 2197, 2744]])

In [16]:
b[[True, False, True, False, False]]

array([[  0,   1,   8],
       [216, 343, 512]])

In [17]:
a[2]        # acceso al tercer elemento del array a

8

In [18]:
a[2:5]      # acceso a los elementos que ocupan las posiciones [2, 5)

array([ 8, 27, 64])

__Una diferencia importante con las listas__, es que las particiones de un ndarray mediante la notación [inicio:fin:paso] son vistas del array original. Todos los cambios realizados en las vistas, se reflejan en el array original:

In [19]:
b = a[0:5]    # no se define un nuevo array, solo una vista de a
b[::] = 0     # acceso a todos los elementos de b y los actualizamos a 0
a

array([   0,    0,    0,    0,    0,  125,  216,  343,  512,  729, 1000,
       1331, 1728, 2197, 2744])

__Copia y original comparten memoria__.
Este tipo de copia se denomina __copia por referencia__.


Este comportamiento evita problemas de memoria. Hay que recordar que __NumPy__ ha sido diseñado para manejar grandes cantidades de datos.

Como  altenativa para la copia de arrays de forma que uno y otro array sean objetos diferentes, podemos usar la función `copy`. Este tipo de copia se denomina copia por valor.


In [5]:
c = a.copy()          # c es una copia de a
c

array([  0,   0,   0,   0,   0, 125, 216, 343, 512, 729], dtype=int32)

In [6]:
c[:] = 0
c , a                # Los cambios en c no afectan al array  a

(array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int32),
 array([  0,   0,   0,   0,   0, 125, 216, 343, 512, 729], dtype=int32))

El acceso a los elementos de un array bidimensional, se realiza indicando los índices separados por una coma.

In [7]:
m = np.array([[2,4,6],[1,2,3]], dtype = 'int')
m

array([[2, 4, 6],
       [1, 2, 3]])

In [8]:
m[1,1]       # fila 2 columna 2

2

In [9]:
m[0,2]     # fila 1 columna 3

6

In [3]:
import numpy as np
b =np.array([[ 0,  1,  2,  3],
       [10, 11, 12, 13],
       [20, 21, 22, 23],
       [30, 31, 32, 33],
       [40, 41, 42, 43]])
b

array([[ 0,  1,  2,  3],
       [10, 11, 12, 13],
       [20, 21, 22, 23],
       [30, 31, 32, 33],
       [40, 41, 42, 43]])

In [4]:
b[-2:, -2:]

array([[32, 33],
       [42, 43]])

In [11]:
b[:, 1]   #Acceso a todos los elementos de la segunda columna

array([ 1, 11, 21, 31, 41])

In [12]:
b[1:3, : ]       # Acceso a los elementos de las filas 2 y 3 de todas las columnas

array([[10, 11, 12, 13],
       [20, 21, 22, 23]])

## Uso de máscaras para selección de partes de un array

Otra forma de acceso a partes de un ndarray es mediante un array de bool que actúa como máscara. 

__Ejemplo__: Supongamos que queremos poner a 0 todos los elementos del array `m` que son menores que 7. 

In [20]:
m = np.array([[22,0], [1,10]], np.float)
mascara = m != 7            # primero seleccionamos los que son menores que 7
mascara                    # matriz booleana

array([[ True,  True],
       [ True,  True]])

Ahora podemos poner a 0 todos los valores menores que 7.

In [12]:
# ahora ponemos a 0 los elementos que cumplen la máscara
t = m[ mascara ] #mscara es acceder a la informacion por contenido 
t

array([0., 1.])

-----------------